spring:
  datasource:
    name: mysqlds
    url: jdbc:mysql://localhost:3306/ignite_spring
    username: developer
    password: developer123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        
server:  
  port: ${PORT:8090}